version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      opentelemetry:
          patterns:
            - "*opentelemetry*"
      patch-dependencies:
          patterns:
            - "*"
          exclude-patterns:
            - "*opentelemetry*"
          update-types:
            - "patch"
      minor-dependencies:
          patterns:
            - "*"
          exclude-patterns:
            - "*opentelemetry*"
          update-types:
            - "minor"
            - "patch"
      major-dependencies:
          patterns:
            - "*"
          exclude-patterns:
            - "*opentelemetry*"
          update-types:
            - "minor"
            - "patch"
            - "major"

  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
