name: Docker Build Upload and eventually Deploy

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:

  build_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build, tag image
      env:
        DOCKER_TAG: tmp_build_tag
      run: |
        docker build -t $DOCKER_TAG .
